### ISSUE TITLE
directory parsing error

### ISSUE THREAD

**Issue by geosone** [fingon/flacs2alacs#1]
it looks like the script has a directrory parsing error it schortens Flac/Queen to Flac/ueen

`root@media:~# flacs2alacs /mnt/mergefs/Music/Flac/ /mnt/mergefs/Music/Alac/
1647 files
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/bin/flacs2alacs", line 44, in convert_flac_to_alac
    st0 = os.stat(srcpath)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/mergefs/Music/Flac/ueen/Absolute Greatest/14 Queen - Who Wants to Live Forever.flac'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/flacs2alacs", line 81, in <module>
    for e in p.map(fun, l):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/mergefs/Music/Flac/ueen/Absolute Greatest/14 Queen - Who Wants to Live Forever.flac'
`

**Comment by fingon** [comment]
Hmm. Odd. I have used it quite a bit. What happens if you do not provide trailing /?

**Comment by geosone** [comment]
you are right without the trailing / its working.
